CREATE TABLE users (
    id            BIGSERIAL PRIMARY KEY,
    first_name    VARCHAR(255) NOT NULL,
    last_name     VARCHAR(255) NOT NULL,
    email         VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    role          VARCHAR(50) NOT NULL DEFAULT 'customer',
    balance_cents BIGINT NOT NULL DEFAULT 1000,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE password_reset_tokens (
    id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT NOT NULL REFERENCES users(id),
    token      TEXT NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE addresses (
    id      INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id),
    street  VARCHAR(255) NOT NULL,
    city    VARCHAR(255) NOT NULL,
    zip     VARCHAR(20) NOT NULL
);

CREATE TABLE books (
    id              BIGSERIAL PRIMARY KEY,
    author          VARCHAR(255) NOT NULL,
    title           VARCHAR(255) NOT NULL,
    pages           INT NOT NULL,
    isbn            VARCHAR(20) NOT NULL,
    price           INT NOT NULL,
    stock           INT NOT NULL,
    url_cover_image VARCHAR(500)
);

CREATE TABLE orders (
    id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT NOT NULL REFERENCES users(id),
    status     VARCHAR(50) NOT NULL,
    total      NUMERIC(10,2) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE order_items (
    id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id   INT NOT NULL REFERENCES orders(id),
    book_id    BIGINT NOT NULL REFERENCES books(id),
    quantity   INT NOT NULL,
    unit_price INT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE reviews (
    id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_id    BIGINT NOT NULL REFERENCES books(id),
    user_id    BIGINT NOT NULL REFERENCES users(id),
    rating     INT NOT NULL,
    comment    TEXT,
    image_url  TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE coupons (
    id               INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code             TEXT NOT NULL UNIQUE,
    discount_percent INT NOT NULL,
    max_uses         INT NOT NULL,
    expires_at       TIMESTAMPTZ NOT NULL,
    used_count       INT NOT NULL DEFAULT 0
);

CREATE TABLE payment_methods (
    id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT NOT NULL REFERENCES users(id),
    card_number VARCHAR(20) NOT NULL,
    card_holder VARCHAR(255) NOT NULL,
    cvv         INT NOT NULL,
    expiry      INT NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);