-- Moves the money columns to integer cents (#6, #18).
--
-- The whole file is one transaction. It is not a stylistic choice: an earlier
-- draft of this migration applied the column rewrites and then failed on the
-- rating check, leaving a database with total_cents and no total. A migration
-- either happens or does not.
BEGIN;
--
-- users.balance_cents was already a BIGINT, but orders.total was NUMERIC(10,2).
-- Go decoded that into a float64 and the checkout path did int64(finalTotal),
-- which truncates: 19.99 became 19, and the order recorded a payment one euro
-- short of the one it computed. Two different types for the same quantity is the
-- root cause, so both sides become cents. No float ever touches money again.
ALTER TABLE orders
    ADD COLUMN total_cents bigint NOT NULL DEFAULT 0;

-- Convert existing totals. The multiplication is exact, because numeric is
-- decimal: 19.99 becomes 1999 and not 1998. Doing this in float64 would
-- reintroduce the bug it is fixing.
UPDATE orders SET total_cents = round(total * 100);

ALTER TABLE orders
    ALTER COLUMN total_cents DROP DEFAULT,
    DROP COLUMN total;

ALTER TABLE order_items
    ADD COLUMN unit_price_cents bigint NOT NULL DEFAULT 0;

UPDATE order_items SET unit_price_cents = round(unit_price * 100);

ALTER TABLE order_items
    ALTER COLUMN unit_price_cents DROP DEFAULT,
    DROP COLUMN unit_price;

-- books.price has the same problem: it is what checkout multiplies by quantity,
-- so a float there is a float in the total.
ALTER TABLE books
    ADD COLUMN price_cents bigint NOT NULL DEFAULT 0;

UPDATE books SET price_cents = round(price * 100);

ALTER TABLE books
    ALTER COLUMN price_cents DROP DEFAULT,
    DROP COLUMN price;

-- Repairs rows that the old, unchecked code wrote, so the constraints below can
-- be added at all.
--
-- This is scoped to a development database, and saying so is the point. Every row
-- removed here is one the application itself should never have been able to
-- create: a review rated -3 or 999, an order line for -3 or 9999 copies. They
-- exist because the tests used to assert those bugs. A production database
-- should not need this block, and if it does, the right response is to inspect
-- the rows rather than delete them.
DELETE FROM reviews WHERE rating < 1 OR rating > 5;

DELETE FROM order_items WHERE quantity < 1 OR quantity > 10;

UPDATE coupons SET discount_percent = 0 WHERE discount_percent < 0 OR discount_percent > 100;
UPDATE coupons SET max_uses = 1 WHERE max_uses < 1;
UPDATE coupons SET used_count = max_uses WHERE used_count > max_uses OR used_count < 0;

-- Constraints that were previously only enforced in Go, where a race could slip
-- past the check (#10, #11, #14).
--
-- One review per book and customer. The service checked this too, but a check
-- followed by an insert is not atomic: two concurrent requests both see "no
-- review" and both insert. The unique constraint is what actually makes it true.
--
CREATE UNIQUE INDEX reviews_one_per_book_and_user
    ON reviews (book_id, user_id);

ALTER TABLE reviews
    ADD CONSTRAINT reviews_rating_range CHECK (rating BETWEEN 1 AND 5);

ALTER TABLE order_items
    ADD CONSTRAINT order_items_quantity_range CHECK (quantity BETWEEN 1 AND 10);

ALTER TABLE coupons
    ADD CONSTRAINT coupons_percent_range CHECK (discount_percent >= 0 AND discount_percent <= 100),
    ADD CONSTRAINT coupons_max_uses_positive CHECK (max_uses > 0),
    ADD CONSTRAINT coupons_used_within_limit CHECK (used_count >= 0 AND used_count <= max_uses);

-- One redemption per coupon per customer (#14). Without it a customer can
-- redeem the same coupon repeatedly and the discount compounds.
CREATE TABLE coupon_redemptions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    coupon_id bigint NOT NULL REFERENCES coupons (id),
    user_id bigint NOT NULL REFERENCES users (id),
    order_id bigint REFERENCES orders (id),
    redeemed_at timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX coupon_redemptions_one_per_user
    ON coupon_redemptions (coupon_id, user_id);

-- There is no backfill of past redemptions, and that is a real gap rather than an
-- oversight: the redeemed-before version of this column was a process-local map
-- in internal/service/discount_ledger.go, so no redemption ever reached the
-- database and there is nothing to recover. A fresh deployment starts with an
-- empty history, which is the correct interpretation.

COMMIT;
