// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: addresses.sql

package db

import (
	"context"
	"database/sql"
)

const createAddress = `-- name: CreateAddress :execresult
INSERT INTO addresses (user_id, street, city, zip)
VALUES (?, ?, ?, ?)
`

type CreateAddressParams struct {
	UserID int64  `json:"user_id"`
	Street string `json:"street"`
	City   string `json:"city"`
	Zip    string `json:"zip"`
}

func (q *Queries) CreateAddress(ctx context.Context, arg CreateAddressParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createAddress,
		arg.UserID,
		arg.Street,
		arg.City,
		arg.Zip,
	)
}

const deleteAddress = `-- name: DeleteAddress :exec
DELETE FROM addresses WHERE id = ?
`

func (q *Queries) DeleteAddress(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteAddress, id)
	return err
}

const getAddressByID = `-- name: GetAddressByID :one
SELECT id, user_id, street, city, zip, created_at FROM addresses WHERE id = ?
`

func (q *Queries) GetAddressByID(ctx context.Context, id int64) (Address, error) {
	row := q.db.QueryRowContext(ctx, getAddressByID, id)
	var i Address
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Street,
		&i.City,
		&i.Zip,
		&i.CreatedAt,
	)
	return i, err
}

const getAddressesByUserID = `-- name: GetAddressesByUserID :many
SELECT id, user_id, street, city, zip, created_at FROM addresses WHERE user_id = ?
`

func (q *Queries) GetAddressesByUserID(ctx context.Context, userID int64) ([]Address, error) {
	rows, err := q.db.QueryContext(ctx, getAddressesByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Address{}
	for rows.Next() {
		var i Address
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Street,
			&i.City,
			&i.Zip,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllAddresses = `-- name: GetAllAddresses :many
SELECT id, user_id, street, city, zip, created_at FROM addresses
`

func (q *Queries) GetAllAddresses(ctx context.Context) ([]Address, error) {
	rows, err := q.db.QueryContext(ctx, getAllAddresses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Address{}
	for rows.Next() {
		var i Address
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Street,
			&i.City,
			&i.Zip,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAddress = `-- name: UpdateAddress :exec
UPDATE addresses
SET user_id = ?, street = ?, city = ?, zip = ?
WHERE id = ?
`

type UpdateAddressParams struct {
	UserID int64  `json:"user_id"`
	Street string `json:"street"`
	City   string `json:"city"`
	Zip    string `json:"zip"`
	ID     int64  `json:"id"`
}

func (q *Queries) UpdateAddress(ctx context.Context, arg UpdateAddressParams) error {
	_, err := q.db.ExecContext(ctx, updateAddress,
		arg.UserID,
		arg.Street,
		arg.City,
		arg.Zip,
		arg.ID,
	)
	return err
}
