// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package db

import (
	"context"
	"database/sql"
)

const createAuditLog = `-- name: CreateAuditLog :execlastid
INSERT INTO audit_log (user_id, user_email, entity, action, entity_id, details)
VALUES (?, ?, ?, ?, ?, ?)
`

type CreateAuditLogParams struct {
	UserID    sql.NullInt64  `json:"user_id"`
	UserEmail sql.NullString `json:"user_email"`
	Entity    string         `json:"entity"`
	Action    string         `json:"action"`
	EntityID  sql.NullInt64  `json:"entity_id"`
	Details   sql.NullString `json:"details"`
}

// One row per operating-history entry. user_id/user_email may be NULL (a
// public catalogue read is not attributed to a staff member), entity_id is the
// row the action touched, and details is a short human line such as the title
// or the backup filename.
func (q *Queries) CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createAuditLog,
		arg.UserID,
		arg.UserEmail,
		arg.Entity,
		arg.Action,
		arg.EntityID,
		arg.Details,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const listAuditLogs = `-- name: ListAuditLogs :many
SELECT id, user_id, user_email, entity, action, entity_id, details, created_at
FROM audit_log
WHERE (entity = ? OR ? = '')
ORDER BY created_at DESC, id DESC
LIMIT ?
`

type ListAuditLogsParams struct {
	Entity string `json:"entity"`
	Limit  int32  `json:"limit"`
}

// The three panels' history, newest first. entity filters the view a tab asks
// for; limit is pages of 200 so a history cannot grow an unbounded response.
// The primary key is AUTO_RANDOM, so id order is not insert order: ORDER BY id DESC
// returns a random slice of the table and the newest pages vanish behind LIMIT.
// created_at is the true sequence of events; id only breaks same-millisecond ties.
func (q *Queries) ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]AuditLog, error) {
	rows, err := q.db.QueryContext(ctx, listAuditLogs, arg.Entity, arg.Entity, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.UserEmail,
			&i.Entity,
			&i.Action,
			&i.EntityID,
			&i.Details,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
