// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: books.sql

package db

import (
	"context"
	"database/sql"
)

const countBooks = `-- name: CountBooks :one
SELECT count(*) FROM books
`

// Dashboard aggregate: the old Stats loaded every row of the table to take
// len() of it. Counting in the database is a single index-only scan.
func (q *Queries) CountBooks(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countBooks)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createBook = `-- name: CreateBook :execresult
INSERT INTO books (author, title, pages, isbn, price_cents, stock, url_cover_image)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateBookParams struct {
	Author        string         `json:"author"`
	Title         string         `json:"title"`
	Pages         int32          `json:"pages"`
	Isbn          string         `json:"isbn"`
	PriceCents    int64          `json:"price_cents"`
	Stock         int32          `json:"stock"`
	UrlCoverImage sql.NullString `json:"url_cover_image"`
}

func (q *Queries) CreateBook(ctx context.Context, arg CreateBookParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createBook,
		arg.Author,
		arg.Title,
		arg.Pages,
		arg.Isbn,
		arg.PriceCents,
		arg.Stock,
		arg.UrlCoverImage,
	)
}

const decrementBookStock = `-- name: DecrementBookStock :execrows
UPDATE books SET stock = stock - ? WHERE id = ? AND stock >= ?
`

type DecrementBookStockParams struct {
	Stock   int32 `json:"stock"`
	ID      int64 `json:"id"`
	Stock_2 int32 `json:"stock_2"`
}

// Conditional on stock, so two concurrent buyers cannot both pass. The caller
// checks the returned row count: one means the stock was really reserved, zero
// means somebody got there first and the whole order has to be abandoned.
func (q *Queries) DecrementBookStock(ctx context.Context, arg DecrementBookStockParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, decrementBookStock, arg.Stock, arg.ID, arg.Stock_2)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteBook = `-- name: DeleteBook :execrows
DELETE FROM books WHERE id = ?
`

// The row count is the whole point of this one. As :exec it was indistinguishable
// from deleting something that exists: no error, no count, a 204 to the panel and
// the book still in the catalogue on the next load. The caller turns a count of
// zero into sql.ErrNoRows, which the transport answers as 404.
func (q *Queries) DeleteBook(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteBook, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getAllBooks = `-- name: GetAllBooks :many
SELECT id, author, title, pages, isbn, price_cents, stock, url_cover_image, created_at FROM books
`

func (q *Queries) GetAllBooks(ctx context.Context) ([]Book, error) {
	rows, err := q.db.QueryContext(ctx, getAllBooks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Book{}
	for rows.Next() {
		var i Book
		if err := rows.Scan(
			&i.ID,
			&i.Author,
			&i.Title,
			&i.Pages,
			&i.Isbn,
			&i.PriceCents,
			&i.Stock,
			&i.UrlCoverImage,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBookByID = `-- name: GetBookByID :one
SELECT id, author, title, pages, isbn, price_cents, stock, url_cover_image, created_at FROM books WHERE id = ?
`

func (q *Queries) GetBookByID(ctx context.Context, id int64) (Book, error) {
	row := q.db.QueryRowContext(ctx, getBookByID, id)
	var i Book
	err := row.Scan(
		&i.ID,
		&i.Author,
		&i.Title,
		&i.Pages,
		&i.Isbn,
		&i.PriceCents,
		&i.Stock,
		&i.UrlCoverImage,
		&i.CreatedAt,
	)
	return i, err
}

const incrementBookStock = `-- name: IncrementBookStock :exec
UPDATE books SET stock = stock + ? WHERE id = ?
`

type IncrementBookStockParams struct {
	Stock int32 `json:"stock"`
	ID    int64 `json:"id"`
}

func (q *Queries) IncrementBookStock(ctx context.Context, arg IncrementBookStockParams) error {
	_, err := q.db.ExecContext(ctx, incrementBookStock, arg.Stock, arg.ID)
	return err
}

const updateBook = `-- name: UpdateBook :exec
UPDATE books
SET author = ?, title = ?, pages = ?, isbn = ?, price_cents = ?, stock = ?, url_cover_image = ?
WHERE id = ?
`

type UpdateBookParams struct {
	Author        string         `json:"author"`
	Title         string         `json:"title"`
	Pages         int32          `json:"pages"`
	Isbn          string         `json:"isbn"`
	PriceCents    int64          `json:"price_cents"`
	Stock         int32          `json:"stock"`
	UrlCoverImage sql.NullString `json:"url_cover_image"`
	ID            int64          `json:"id"`
}

func (q *Queries) UpdateBook(ctx context.Context, arg UpdateBookParams) error {
	_, err := q.db.ExecContext(ctx, updateBook,
		arg.Author,
		arg.Title,
		arg.Pages,
		arg.Isbn,
		arg.PriceCents,
		arg.Stock,
		arg.UrlCoverImage,
		arg.ID,
	)
	return err
}
