// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: coupon_redemptions.sql

package db

import (
	"context"
	"database/sql"
)

const countCouponRedemptions = `-- name: CountCouponRedemptions :one
SELECT count(*) FROM coupon_redemptions WHERE coupon_id = ?
`

func (q *Queries) CountCouponRedemptions(ctx context.Context, couponID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countCouponRedemptions, couponID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCouponRedemption = `-- name: CreateCouponRedemption :execresult
INSERT INTO coupon_redemptions (coupon_id, user_id, order_id)
VALUES (?, ?, ?)
`

type CreateCouponRedemptionParams struct {
	CouponID int64         `json:"coupon_id"`
	UserID   int64         `json:"user_id"`
	OrderID  sql.NullInt64 `json:"order_id"`
}

// The record that a customer has spent a coupon. The unique index on
// (coupon_id, user_id) is what makes a second attempt fail, and it fails in the
// database rather than in a check that another request can slip between.
func (q *Queries) CreateCouponRedemption(ctx context.Context, arg CreateCouponRedemptionParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createCouponRedemption, arg.CouponID, arg.UserID, arg.OrderID)
}

const deleteCouponRedemptionByOrder = `-- name: DeleteCouponRedemptionByOrder :exec
DELETE FROM coupon_redemptions WHERE order_id = ?
`

// Undoes a redemption when the order it belonged to is rolled back by hand.
func (q *Queries) DeleteCouponRedemptionByOrder(ctx context.Context, orderID sql.NullInt64) error {
	_, err := q.db.ExecContext(ctx, deleteCouponRedemptionByOrder, orderID)
	return err
}

const getCouponRedemption = `-- name: GetCouponRedemption :one
SELECT id, coupon_id, user_id, order_id, redeemed_at FROM coupon_redemptions WHERE coupon_id = ? AND user_id = ?
`

type GetCouponRedemptionParams struct {
	CouponID int64 `json:"coupon_id"`
	UserID   int64 `json:"user_id"`
}

func (q *Queries) GetCouponRedemption(ctx context.Context, arg GetCouponRedemptionParams) (CouponRedemption, error) {
	row := q.db.QueryRowContext(ctx, getCouponRedemption, arg.CouponID, arg.UserID)
	var i CouponRedemption
	err := row.Scan(
		&i.ID,
		&i.CouponID,
		&i.UserID,
		&i.OrderID,
		&i.RedeemedAt,
	)
	return i, err
}
