// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: coupons.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const countCoupons = `-- name: CountCoupons :one
SELECT count(*) FROM coupons
`

// Dashboard aggregate: the old Stats loaded every row of the table to take
// len() of it. Counting in the database is a single index-only scan.
func (q *Queries) CountCoupons(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countCoupons)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCoupon = `-- name: CreateCoupon :execresult
INSERT INTO coupons (code, discount_percent, max_uses, expires_at, used_count)
VALUES (?, ?, ?, ?, ?)
`

type CreateCouponParams struct {
	Code            string    `json:"code"`
	DiscountPercent int32     `json:"discount_percent"`
	MaxUses         int32     `json:"max_uses"`
	ExpiresAt       time.Time `json:"expires_at"`
	UsedCount       int32     `json:"used_count"`
}

func (q *Queries) CreateCoupon(ctx context.Context, arg CreateCouponParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createCoupon,
		arg.Code,
		arg.DiscountPercent,
		arg.MaxUses,
		arg.ExpiresAt,
		arg.UsedCount,
	)
}

const deleteCoupon = `-- name: DeleteCoupon :execrows
DELETE FROM coupons WHERE id = ?
`

// The row count is what distinguishes deleting a coupon from deleting nothing.
// As :exec the panel got a 204 and a "borrado" for a coupon that was never
// there. The caller turns zero into sql.ErrNoRows, which is a 404.
func (q *Queries) DeleteCoupon(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteCoupon, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getAllCoupons = `-- name: GetAllCoupons :many
SELECT id, code, discount_percent, max_uses, expires_at, used_count, created_at FROM coupons
`

func (q *Queries) GetAllCoupons(ctx context.Context) ([]Coupon, error) {
	rows, err := q.db.QueryContext(ctx, getAllCoupons)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Coupon{}
	for rows.Next() {
		var i Coupon
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.DiscountPercent,
			&i.MaxUses,
			&i.ExpiresAt,
			&i.UsedCount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCouponByCode = `-- name: GetCouponByCode :one
SELECT id, code, discount_percent, max_uses, expires_at, used_count, created_at FROM coupons WHERE code = ?
`

func (q *Queries) GetCouponByCode(ctx context.Context, code string) (Coupon, error) {
	row := q.db.QueryRowContext(ctx, getCouponByCode, code)
	var i Coupon
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.DiscountPercent,
		&i.MaxUses,
		&i.ExpiresAt,
		&i.UsedCount,
		&i.CreatedAt,
	)
	return i, err
}

const getCouponByID = `-- name: GetCouponByID :one
SELECT id, code, discount_percent, max_uses, expires_at, used_count, created_at FROM coupons WHERE id = ?
`

func (q *Queries) GetCouponByID(ctx context.Context, id int64) (Coupon, error) {
	row := q.db.QueryRowContext(ctx, getCouponByID, id)
	var i Coupon
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.DiscountPercent,
		&i.MaxUses,
		&i.ExpiresAt,
		&i.UsedCount,
		&i.CreatedAt,
	)
	return i, err
}

const giveBackCouponUse = `-- name: GiveBackCouponUse :exec
UPDATE coupons SET used_count = used_count - 1 WHERE id = ? AND used_count > 0
`

// Returns a use when an order is abandoned after the coupon was spent, so a
// failed checkout does not permanently consume a customer's single use.
func (q *Queries) GiveBackCouponUse(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, giveBackCouponUse, id)
	return err
}

const redeemCoupon = `-- name: RedeemCoupon :execrows
UPDATE coupons
SET used_count = used_count + 1
WHERE id = ?
  AND used_count < max_uses
  AND (expires_at IS NULL OR expires_at > CURRENT_TIMESTAMP)
`

// The redemption, done as a single conditional update.
//
// used_count < max_uses and the expiry are both part of the WHERE clause, so two
// concurrent redemptions of the last remaining use cannot both match: the second
// one updates zero rows. The old code read the count, compared it in Go and
// wrote it back, which is a time-of-check to time-of-use gap wide enough for a
// dozen parallel requests to walk through together.
//
// The caller must check the returned row count. Zero means the coupon was
// exhausted or expired, and the whole transaction has to be abandoned.
func (q *Queries) RedeemCoupon(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, redeemCoupon, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateCoupon = `-- name: UpdateCoupon :exec
UPDATE coupons
SET code = ?, discount_percent = ?, max_uses = ?, expires_at = ?, used_count = ?
WHERE id = ?
`

type UpdateCouponParams struct {
	Code            string    `json:"code"`
	DiscountPercent int32     `json:"discount_percent"`
	MaxUses         int32     `json:"max_uses"`
	ExpiresAt       time.Time `json:"expires_at"`
	UsedCount       int32     `json:"used_count"`
	ID              int64     `json:"id"`
}

func (q *Queries) UpdateCoupon(ctx context.Context, arg UpdateCouponParams) error {
	_, err := q.db.ExecContext(ctx, updateCoupon,
		arg.Code,
		arg.DiscountPercent,
		arg.MaxUses,
		arg.ExpiresAt,
		arg.UsedCount,
		arg.ID,
	)
	return err
}
