// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
	"time"
)

type Address struct {
	ID        int64     `json:"id"`
	UserID    int64     `json:"user_id"`
	Street    string    `json:"street"`
	City      string    `json:"city"`
	Zip       string    `json:"zip"`
	CreatedAt time.Time `json:"created_at"`
}

type AuditLog struct {
	ID        int64          `json:"id"`
	UserID    sql.NullInt64  `json:"user_id"`
	UserEmail sql.NullString `json:"user_email"`
	Entity    string         `json:"entity"`
	Action    string         `json:"action"`
	EntityID  sql.NullInt64  `json:"entity_id"`
	Details   sql.NullString `json:"details"`
	CreatedAt time.Time      `json:"created_at"`
}

type Book struct {
	ID            int64          `json:"id"`
	Author        string         `json:"author"`
	Title         string         `json:"title"`
	Pages         int32          `json:"pages"`
	Isbn          string         `json:"isbn"`
	PriceCents    int64          `json:"price_cents"`
	Stock         int32          `json:"stock"`
	UrlCoverImage sql.NullString `json:"url_cover_image"`
	CreatedAt     time.Time      `json:"created_at"`
}

type Coupon struct {
	ID              int64     `json:"id"`
	Code            string    `json:"code"`
	DiscountPercent int32     `json:"discount_percent"`
	MaxUses         int32     `json:"max_uses"`
	ExpiresAt       time.Time `json:"expires_at"`
	UsedCount       int32     `json:"used_count"`
	CreatedAt       time.Time `json:"created_at"`
}

type CouponRedemption struct {
	ID         int64         `json:"id"`
	CouponID   int64         `json:"coupon_id"`
	UserID     int64         `json:"user_id"`
	OrderID    sql.NullInt64 `json:"order_id"`
	RedeemedAt time.Time     `json:"redeemed_at"`
}

type Order struct {
	ID            int64         `json:"id"`
	UserID        int64         `json:"user_id"`
	Status        string        `json:"status"`
	SubtotalCents int64         `json:"subtotal_cents"`
	DiscountCents int64         `json:"discount_cents"`
	TotalCents    int64         `json:"total_cents"`
	CouponID      sql.NullInt64 `json:"coupon_id"`
	CreatedAt     time.Time     `json:"created_at"`
}

type OrderItem struct {
	ID             int64     `json:"id"`
	OrderID        int64     `json:"order_id"`
	BookID         int64     `json:"book_id"`
	Quantity       int32     `json:"quantity"`
	UnitPriceCents int64     `json:"unit_price_cents"`
	CreatedAt      time.Time `json:"created_at"`
}

type PasswordResetToken struct {
	ID         int64         `json:"id"`
	UserID     int64         `json:"user_id"`
	Token      string        `json:"token"`
	ExpiresAt  time.Time     `json:"expires_at"`
	UsedAt     sql.NullTime  `json:"used_at"`
	CreatedAt  time.Time     `json:"created_at"`
	LiveUserID sql.NullInt64 `json:"live_user_id"`
}

type PaymentMethod struct {
	ID          int64     `json:"id"`
	UserID      int64     `json:"user_id"`
	Brand       string    `json:"brand"`
	Last4       string    `json:"last4"`
	ExpiryMonth int16     `json:"expiry_month"`
	ExpiryYear  int16     `json:"expiry_year"`
	CreatedAt   time.Time `json:"created_at"`
}

type Review struct {
	ID        int64          `json:"id"`
	BookID    int64          `json:"book_id"`
	UserID    int64          `json:"user_id"`
	Rating    int32          `json:"rating"`
	Comment   sql.NullString `json:"comment"`
	ImageUrl  string         `json:"image_url"`
	CreatedAt time.Time      `json:"created_at"`
}

type User struct {
	ID           int64     `json:"id"`
	FirstName    string    `json:"first_name"`
	LastName     string    `json:"last_name"`
	Email        string    `json:"email"`
	PasswordHash string    `json:"password_hash"`
	Role         string    `json:"role"`
	BalanceCents int64     `json:"balance_cents"`
	TokenVersion int32     `json:"token_version"`
	CreatedAt    time.Time `json:"created_at"`
	IsActive     bool      `json:"is_active"`
}
