// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: orders.sql

package db

import (
	"context"
	"database/sql"
)

const countOrders = `-- name: CountOrders :one

SELECT count(*) FROM orders
`

// CountOrders and SumOrderTotals exist for the admin dashboard, which used to load
// every row of every table just to count them and add up a column: linear in the
// size of the shop, and worse with every visit to the panel.
func (q *Queries) CountOrders(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countOrders)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createOrder = `-- name: CreateOrder :execresult
INSERT INTO orders (user_id, status, subtotal_cents, discount_cents, total_cents, coupon_id)
VALUES (?, ?, ?, ?, ?, ?)
`

type CreateOrderParams struct {
	UserID        int64         `json:"user_id"`
	Status        string        `json:"status"`
	SubtotalCents int64         `json:"subtotal_cents"`
	DiscountCents int64         `json:"discount_cents"`
	TotalCents    int64         `json:"total_cents"`
	CouponID      sql.NullInt64 `json:"coupon_id"`
}

// The four money columns are set together, from values the service computed
// inside the transaction. subtotal_cents and discount_cents are stored alongside
// the total so the charge can be checked against the lines that produced it
// later, without trusting whatever the ledger used to say.
func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createOrder,
		arg.UserID,
		arg.Status,
		arg.SubtotalCents,
		arg.DiscountCents,
		arg.TotalCents,
		arg.CouponID,
	)
}

const deleteOrder = `-- name: DeleteOrder :exec
DELETE FROM orders WHERE id = ?
`

func (q *Queries) DeleteOrder(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteOrder, id)
	return err
}

const getAllOrders = `-- name: GetAllOrders :many
SELECT id, user_id, status, subtotal_cents, discount_cents, total_cents, coupon_id, created_at FROM orders
`

func (q *Queries) GetAllOrders(ctx context.Context) ([]Order, error) {
	rows, err := q.db.QueryContext(ctx, getAllOrders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Order{}
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Status,
			&i.SubtotalCents,
			&i.DiscountCents,
			&i.TotalCents,
			&i.CouponID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOrderByID = `-- name: GetOrderByID :one
SELECT id, user_id, status, subtotal_cents, discount_cents, total_cents, coupon_id, created_at FROM orders WHERE id = ?
`

func (q *Queries) GetOrderByID(ctx context.Context, id int64) (Order, error) {
	row := q.db.QueryRowContext(ctx, getOrderByID, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.SubtotalCents,
		&i.DiscountCents,
		&i.TotalCents,
		&i.CouponID,
		&i.CreatedAt,
	)
	return i, err
}

const getOrdersByUserID = `-- name: GetOrdersByUserID :many
SELECT id, user_id, status, subtotal_cents, discount_cents, total_cents, coupon_id, created_at FROM orders WHERE user_id = ? ORDER BY created_at DESC, id DESC
`

// A customer listing their own orders. The global listing is admin-only, so
// this is what the frontend uses.
func (q *Queries) GetOrdersByUserID(ctx context.Context, userID int64) ([]Order, error) {
	rows, err := q.db.QueryContext(ctx, getOrdersByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Order{}
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Status,
			&i.SubtotalCents,
			&i.DiscountCents,
			&i.TotalCents,
			&i.CouponID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumOrderTotals = `-- name: SumOrderTotals :one
SELECT COALESCE(CAST(SUM(total_cents) AS SIGNED), 0)
FROM orders
WHERE status IN ('completed', 'shipped', 'delivered')
`

// Revenue, not volume. The panel labels this figure what it is: money actually
// taken. An order that was cancelled or refunded has had its money returned, so
// summing it in would overstate the shop by exactly the refunds it granted.
// 'pending' is not money taken either; nothing has been charged yet.
//
// The CAST is not decoration. MySQL widens SUM() over an integer column to
// DECIMAL so the result cannot overflow, and the driver hands a DECIMAL back as
// []byte. Left uncast, sqlc types the column as interface{}, and the store
// received bytes it could only reject, which is why GET /admin/stats answered
// 500 with "unexpected type for sum" and took the whole panel down with it.
// CAST(... AS SIGNED) makes TiDB return BIGINT, so the sum is an int64 from the
// wire to the JSON, and no amount of money passes through a float.
func (q *Queries) SumOrderTotals(ctx context.Context) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, sumOrderTotals)
	var coalesce interface{}
	err := row.Scan(&coalesce)
	return coalesce, err
}

const updateOrder = `-- name: UpdateOrder :exec
UPDATE orders
SET status = ?, subtotal_cents = ?, discount_cents = ?, total_cents = ?, coupon_id = ?
WHERE id = ?
`

type UpdateOrderParams struct {
	Status        string        `json:"status"`
	SubtotalCents int64         `json:"subtotal_cents"`
	DiscountCents int64         `json:"discount_cents"`
	TotalCents    int64         `json:"total_cents"`
	CouponID      sql.NullInt64 `json:"coupon_id"`
	ID            int64         `json:"id"`
}

// user_id is absent on purpose. Reassigning an order to a different account is a
// takeover primitive, and no caller should be able to do it by editing one.
func (q *Queries) UpdateOrder(ctx context.Context, arg UpdateOrderParams) error {
	_, err := q.db.ExecContext(ctx, updateOrder,
		arg.Status,
		arg.SubtotalCents,
		arg.DiscountCents,
		arg.TotalCents,
		arg.CouponID,
		arg.ID,
	)
	return err
}
