// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: order_items.sql

package db

import (
	"context"
	"database/sql"
)

const createOrderItem = `-- name: CreateOrderItem :execresult
INSERT INTO order_items (order_id, book_id, quantity, unit_price_cents)
VALUES (?, ?, ?, ?)
`

type CreateOrderItemParams struct {
	OrderID        int64 `json:"order_id"`
	BookID         int64 `json:"book_id"`
	Quantity       int32 `json:"quantity"`
	UnitPriceCents int64 `json:"unit_price_cents"`
}

func (q *Queries) CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createOrderItem,
		arg.OrderID,
		arg.BookID,
		arg.Quantity,
		arg.UnitPriceCents,
	)
}

const deleteOrderItem = `-- name: DeleteOrderItem :exec
DELETE FROM order_items WHERE id = ?
`

func (q *Queries) DeleteOrderItem(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteOrderItem, id)
	return err
}

const getAllOrderItems = `-- name: GetAllOrderItems :many
SELECT id, order_id, book_id, quantity, unit_price_cents, created_at FROM order_items
`

func (q *Queries) GetAllOrderItems(ctx context.Context) ([]OrderItem, error) {
	rows, err := q.db.QueryContext(ctx, getAllOrderItems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrderItem{}
	for rows.Next() {
		var i OrderItem
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.BookID,
			&i.Quantity,
			&i.UnitPriceCents,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOrderItemByID = `-- name: GetOrderItemByID :one
SELECT id, order_id, book_id, quantity, unit_price_cents, created_at FROM order_items WHERE id = ?
`

func (q *Queries) GetOrderItemByID(ctx context.Context, id int64) (OrderItem, error) {
	row := q.db.QueryRowContext(ctx, getOrderItemByID, id)
	var i OrderItem
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.BookID,
		&i.Quantity,
		&i.UnitPriceCents,
		&i.CreatedAt,
	)
	return i, err
}

const getOrderItemOwnerID = `-- name: GetOrderItemOwnerID :one
SELECT o.user_id
FROM order_items oi
JOIN orders o ON o.id = oi.order_id
WHERE oi.id = ?
`

// The account that owns an order item is two joins away, and the handler needs
// it to answer "is this yours" before touching the row. Returning the owner
// rather than the item keeps the check in one place instead of every caller
// having to remember to walk the relationship.
func (q *Queries) GetOrderItemOwnerID(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, getOrderItemOwnerID, id)
	var user_id int64
	err := row.Scan(&user_id)
	return user_id, err
}

const getOrderItemsByOrderID = `-- name: GetOrderItemsByOrderID :many
SELECT id, order_id, book_id, quantity, unit_price_cents, created_at FROM order_items WHERE order_id = ?
`

func (q *Queries) GetOrderItemsByOrderID(ctx context.Context, orderID int64) ([]OrderItem, error) {
	rows, err := q.db.QueryContext(ctx, getOrderItemsByOrderID, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrderItem{}
	for rows.Next() {
		var i OrderItem
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.BookID,
			&i.Quantity,
			&i.UnitPriceCents,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrderItem = `-- name: UpdateOrderItem :exec
UPDATE order_items
SET order_id = ?, book_id = ?, quantity = ?, unit_price_cents = ?
WHERE id = ?
`

type UpdateOrderItemParams struct {
	OrderID        int64 `json:"order_id"`
	BookID         int64 `json:"book_id"`
	Quantity       int32 `json:"quantity"`
	UnitPriceCents int64 `json:"unit_price_cents"`
	ID             int64 `json:"id"`
}

func (q *Queries) UpdateOrderItem(ctx context.Context, arg UpdateOrderItemParams) error {
	_, err := q.db.ExecContext(ctx, updateOrderItem,
		arg.OrderID,
		arg.BookID,
		arg.Quantity,
		arg.UnitPriceCents,
		arg.ID,
	)
	return err
}
