// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: password_reset_tokens.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const consumePasswordResetToken = `-- name: ConsumePasswordResetToken :execrows
UPDATE password_reset_tokens
SET used_at = CURRENT_TIMESTAMP
WHERE token = ?
  AND used_at IS NULL
  AND expires_at > CURRENT_TIMESTAMP
`

// Single-use redemption, enforced atomically.
//
// The used_at IS NULL and expires_at > now() predicates live in the UPDATE, not
// in a prior SELECT. That is what makes replay impossible under concurrency: two
// simultaneous requests both try to stamp the same row, the database serialises
// them, and the loser matches zero rows instead of also succeeding. Checking
// expiry in Go before this call would leave the window open between the read and
// the write.
func (q *Queries) ConsumePasswordResetToken(ctx context.Context, token string) (int64, error) {
	result, err := q.db.ExecContext(ctx, consumePasswordResetToken, token)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const createPasswordResetToken = `-- name: CreatePasswordResetToken :execresult
INSERT INTO password_reset_tokens (user_id, token, expires_at)
VALUES (?, ?, ?)
`

type CreatePasswordResetTokenParams struct {
	UserID    int64     `json:"user_id"`
	Token     string    `json:"token"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) CreatePasswordResetToken(ctx context.Context, arg CreatePasswordResetTokenParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createPasswordResetToken, arg.UserID, arg.Token, arg.ExpiresAt)
}

const deletePasswordResetToken = `-- name: DeletePasswordResetToken :exec
DELETE FROM password_reset_tokens WHERE id = ?
`

func (q *Queries) DeletePasswordResetToken(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deletePasswordResetToken, id)
	return err
}

const getAllPasswordResetTokens = `-- name: GetAllPasswordResetTokens :many
SELECT id, user_id, token, expires_at, used_at, created_at, live_user_id FROM password_reset_tokens
`

func (q *Queries) GetAllPasswordResetTokens(ctx context.Context) ([]PasswordResetToken, error) {
	rows, err := q.db.QueryContext(ctx, getAllPasswordResetTokens)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PasswordResetToken{}
	for rows.Next() {
		var i PasswordResetToken
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Token,
			&i.ExpiresAt,
			&i.UsedAt,
			&i.CreatedAt,
			&i.LiveUserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPasswordResetTokenByID = `-- name: GetPasswordResetTokenByID :one
SELECT id, user_id, token, expires_at, used_at, created_at, live_user_id FROM password_reset_tokens WHERE id = ?
`

func (q *Queries) GetPasswordResetTokenByID(ctx context.Context, id int64) (PasswordResetToken, error) {
	row := q.db.QueryRowContext(ctx, getPasswordResetTokenByID, id)
	var i PasswordResetToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
		&i.LiveUserID,
	)
	return i, err
}

const getPasswordResetTokenByToken = `-- name: GetPasswordResetTokenByToken :one
SELECT id, user_id, token, expires_at, used_at, created_at, live_user_id FROM password_reset_tokens WHERE token = ?
`

func (q *Queries) GetPasswordResetTokenByToken(ctx context.Context, token string) (PasswordResetToken, error) {
	row := q.db.QueryRowContext(ctx, getPasswordResetTokenByToken, token)
	var i PasswordResetToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
		&i.LiveUserID,
	)
	return i, err
}

const revokePasswordResetTokensForUser = `-- name: RevokePasswordResetTokensForUser :execrows
UPDATE password_reset_tokens
SET used_at = CURRENT_TIMESTAMP
WHERE user_id = ? AND used_at IS NULL
`

// Requesting a new code must invalidate the previous one, so an intercepted
// older email cannot be used after the user asked for a fresh code.
func (q *Queries) RevokePasswordResetTokensForUser(ctx context.Context, userID int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, revokePasswordResetTokensForUser, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updatePasswordResetToken = `-- name: UpdatePasswordResetToken :exec
UPDATE password_reset_tokens
SET user_id = ?, token = ?, expires_at = ?
WHERE id = ?
`

type UpdatePasswordResetTokenParams struct {
	UserID    int64     `json:"user_id"`
	Token     string    `json:"token"`
	ExpiresAt time.Time `json:"expires_at"`
	ID        int64     `json:"id"`
}

func (q *Queries) UpdatePasswordResetToken(ctx context.Context, arg UpdatePasswordResetTokenParams) error {
	_, err := q.db.ExecContext(ctx, updatePasswordResetToken,
		arg.UserID,
		arg.Token,
		arg.ExpiresAt,
		arg.ID,
	)
	return err
}
