// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payment_methods.sql

package db

import (
	"context"
	"database/sql"
)

const countPaymentMethods = `-- name: CountPaymentMethods :one
SELECT count(*) FROM payment_methods
`

// Dashboard aggregate: the old Stats loaded every row of the table to take
// len() of it. Counting in the database is a single index-only scan.
func (q *Queries) CountPaymentMethods(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPaymentMethods)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPaymentMethod = `-- name: CreatePaymentMethod :execresult
INSERT INTO payment_methods (user_id, brand, last4, expiry_month, expiry_year)
VALUES (?, ?, ?, ?, ?)
`

type CreatePaymentMethodParams struct {
	UserID      int64  `json:"user_id"`
	Brand       string `json:"brand"`
	Last4       string `json:"last4"`
	ExpiryMonth int16  `json:"expiry_month"`
	ExpiryYear  int16  `json:"expiry_year"`
}

// brand and last4 only. There is no column for the card number, which is the
// point: the value the client sent is not storable.
func (q *Queries) CreatePaymentMethod(ctx context.Context, arg CreatePaymentMethodParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createPaymentMethod,
		arg.UserID,
		arg.Brand,
		arg.Last4,
		arg.ExpiryMonth,
		arg.ExpiryYear,
	)
}

const deletePaymentMethod = `-- name: DeletePaymentMethod :exec
DELETE FROM payment_methods WHERE id = ?
`

func (q *Queries) DeletePaymentMethod(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deletePaymentMethod, id)
	return err
}

const getPaymentMethodByID = `-- name: GetPaymentMethodByID :one

SELECT id, user_id, brand, last4, expiry_month, expiry_year, created_at FROM payment_methods WHERE id = ?
`

// There is deliberately no "list every payment method" query. It was here for
// the #12 fix and it was never routed, so deleting it removed a query whose
// only behaviour is to hand back every card in the table to whoever asks.
func (q *Queries) GetPaymentMethodByID(ctx context.Context, id int64) (PaymentMethod, error) {
	row := q.db.QueryRowContext(ctx, getPaymentMethodByID, id)
	var i PaymentMethod
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Brand,
		&i.Last4,
		&i.ExpiryMonth,
		&i.ExpiryYear,
		&i.CreatedAt,
	)
	return i, err
}

const getPaymentMethodsByUserID = `-- name: GetPaymentMethodsByUserID :many
SELECT id, user_id, brand, last4, expiry_month, expiry_year, created_at FROM payment_methods WHERE user_id = ?
`

func (q *Queries) GetPaymentMethodsByUserID(ctx context.Context, userID int64) ([]PaymentMethod, error) {
	rows, err := q.db.QueryContext(ctx, getPaymentMethodsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PaymentMethod{}
	for rows.Next() {
		var i PaymentMethod
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Brand,
			&i.Last4,
			&i.ExpiryMonth,
			&i.ExpiryYear,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePaymentMethod = `-- name: UpdatePaymentMethod :exec
UPDATE payment_methods
SET brand = ?, last4 = ?, expiry_month = ?, expiry_year = ?
WHERE id = ?
`

type UpdatePaymentMethodParams struct {
	Brand       string `json:"brand"`
	Last4       string `json:"last4"`
	ExpiryMonth int16  `json:"expiry_month"`
	ExpiryYear  int16  `json:"expiry_year"`
	ID          int64  `json:"id"`
}

// user_id is deliberately absent. Reassigning a card to another account is a
// takeover primitive, and the handler already forces the stored owner.
func (q *Queries) UpdatePaymentMethod(ctx context.Context, arg UpdatePaymentMethodParams) error {
	_, err := q.db.ExecContext(ctx, updatePaymentMethod,
		arg.Brand,
		arg.Last4,
		arg.ExpiryMonth,
		arg.ExpiryYear,
		arg.ID,
	)
	return err
}
