// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	// Invalidates every session issued before this call: the middleware compares the
	// token's "ver" claim against this value on each request.
	BumpTokenVersion(ctx context.Context, id int64) error
	// Single-use redemption, enforced atomically.
	//
	// The used_at IS NULL and expires_at > now() predicates live in the UPDATE, not
	// in a prior SELECT. That is what makes replay impossible under concurrency: two
	// simultaneous requests both try to stamp the same row, the database serialises
	// them, and the loser matches zero rows instead of also succeeding. Checking
	// expiry in Go before this call would leave the window open between the read and
	// the write.
	ConsumePasswordResetToken(ctx context.Context, token string) (int64, error)
	// Dashboard aggregate: the old Stats loaded every row of the table to take
	// len() of it. Counting in the database is a single index-only scan.
	CountBooks(ctx context.Context) (int64, error)
	CountCouponRedemptions(ctx context.Context, couponID int64) (int64, error)
	// Dashboard aggregate: the old Stats loaded every row of the table to take
	// len() of it. Counting in the database is a single index-only scan.
	CountCoupons(ctx context.Context) (int64, error)
	// CountOrders and SumOrderTotals exist for the admin dashboard, which used to load
	// every row of every table just to count them and add up a column: linear in the
	// size of the shop, and worse with every visit to the panel.
	CountOrders(ctx context.Context) (int64, error)
	// Dashboard aggregate: the old Stats loaded every row of the table to take
	// len() of it. Counting in the database is a single index-only scan.
	CountPaymentMethods(ctx context.Context) (int64, error)
	// Dashboard aggregate. Stats used to call GetAllUsers and take len() of the
	// result, so asking for one number cost a full table read and a full
	// materialisation of every user in the shop.
	CountUsers(ctx context.Context) (int64, error)
	CreateAddress(ctx context.Context, arg CreateAddressParams) (sql.Result, error)
	// One row per operating-history entry. user_id/user_email may be NULL (a
	// public catalogue read is not attributed to a staff member), entity_id is the
	// row the action touched, and details is a short human line such as the title
	// or the backup filename.
	CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (int64, error)
	CreateBook(ctx context.Context, arg CreateBookParams) (sql.Result, error)
	CreateCoupon(ctx context.Context, arg CreateCouponParams) (sql.Result, error)
	// The record that a customer has spent a coupon. The unique index on
	// (coupon_id, user_id) is what makes a second attempt fail, and it fails in the
	// database rather than in a check that another request can slip between.
	CreateCouponRedemption(ctx context.Context, arg CreateCouponRedemptionParams) (sql.Result, error)
	// The four money columns are set together, from values the service computed
	// inside the transaction. subtotal_cents and discount_cents are stored alongside
	// the total so the charge can be checked against the lines that produced it
	// later, without trusting whatever the ledger used to say.
	CreateOrder(ctx context.Context, arg CreateOrderParams) (sql.Result, error)
	CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (sql.Result, error)
	CreatePasswordResetToken(ctx context.Context, arg CreatePasswordResetTokenParams) (sql.Result, error)
	// brand and last4 only. There is no column for the card number, which is the
	// point: the value the client sent is not storable.
	CreatePaymentMethod(ctx context.Context, arg CreatePaymentMethodParams) (sql.Result, error)
	CreateReview(ctx context.Context, arg CreateReviewParams) (sql.Result, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (sql.Result, error)
	// The refund half of a debit. Used when an order is cancelled, and it is the
	// only way a balance goes up outside the seed.
	CreditUserBalance(ctx context.Context, arg CreditUserBalanceParams) error
	DebitUserBalance(ctx context.Context, arg DebitUserBalanceParams) error
	// The debit and the affordability check are the same statement.
	//
	// The old DebitUserBalance subtracted unconditionally, after the service had
	// read the balance and compared it in Go. Two requests spending the same balance
	// both read a sufficient figure and both debited, driving it negative. With the
	// comparison in the WHERE clause the second update matches no rows, and the
	// caller sees zero affected and aborts.
	//
	// RowsAffected is the answer; there is nothing to read afterwards.
	DebitUserBalanceIfSufficient(ctx context.Context, arg DebitUserBalanceIfSufficientParams) (int64, error)
	// Conditional on stock, so two concurrent buyers cannot both pass. The caller
	// checks the returned row count: one means the stock was really reserved, zero
	// means somebody got there first and the whole order has to be abandoned.
	DecrementBookStock(ctx context.Context, arg DecrementBookStockParams) (int64, error)
	DeleteAddress(ctx context.Context, id int64) error
	// The row count is the whole point of this one. As :exec it was indistinguishable
	// from deleting something that exists: no error, no count, a 204 to the panel and
	// the book still in the catalogue on the next load. The caller turns a count of
	// zero into sql.ErrNoRows, which the transport answers as 404.
	DeleteBook(ctx context.Context, id int64) (int64, error)
	// The row count is what distinguishes deleting a coupon from deleting nothing.
	// As :exec the panel got a 204 and a "borrado" for a coupon that was never
	// there. The caller turns zero into sql.ErrNoRows, which is a 404.
	DeleteCoupon(ctx context.Context, id int64) (int64, error)
	// Undoes a redemption when the order it belonged to is rolled back by hand.
	DeleteCouponRedemptionByOrder(ctx context.Context, orderID sql.NullInt64) error
	DeleteOrder(ctx context.Context, id int64) error
	DeleteOrderItem(ctx context.Context, id int64) error
	DeletePasswordResetToken(ctx context.Context, id int64) error
	DeletePaymentMethod(ctx context.Context, id int64) error
	DeleteReview(ctx context.Context, id int64) error
	// As :exec, deleting an account that does not exist was indistinguishable from
	// deleting one that did, and the panel reported the success either way. Zero
	// rows becomes sql.ErrNoRows at the store, which is a 404.
	DeleteUser(ctx context.Context, id int64) (int64, error)
	GetAddressByID(ctx context.Context, id int64) (Address, error)
	GetAddressesByUserID(ctx context.Context, userID int64) ([]Address, error)
	GetAllAddresses(ctx context.Context) ([]Address, error)
	GetAllBooks(ctx context.Context) ([]Book, error)
	GetAllCoupons(ctx context.Context) ([]Coupon, error)
	GetAllOrderItems(ctx context.Context) ([]OrderItem, error)
	GetAllOrders(ctx context.Context) ([]Order, error)
	GetAllPasswordResetTokens(ctx context.Context) ([]PasswordResetToken, error)
	GetAllReviews(ctx context.Context) ([]Review, error)
	GetAllUsers(ctx context.Context) ([]User, error)
	GetBookByID(ctx context.Context, id int64) (Book, error)
	GetCouponByCode(ctx context.Context, code string) (Coupon, error)
	GetCouponByID(ctx context.Context, id int64) (Coupon, error)
	GetCouponRedemption(ctx context.Context, arg GetCouponRedemptionParams) (CouponRedemption, error)
	GetOrderByID(ctx context.Context, id int64) (Order, error)
	GetOrderItemByID(ctx context.Context, id int64) (OrderItem, error)
	// The account that owns an order item is two joins away, and the handler needs
	// it to answer "is this yours" before touching the row. Returning the owner
	// rather than the item keeps the check in one place instead of every caller
	// having to remember to walk the relationship.
	GetOrderItemOwnerID(ctx context.Context, id int64) (int64, error)
	GetOrderItemsByOrderID(ctx context.Context, orderID int64) ([]OrderItem, error)
	// A customer listing their own orders. The global listing is admin-only, so
	// this is what the frontend uses.
	GetOrdersByUserID(ctx context.Context, userID int64) ([]Order, error)
	GetPasswordResetTokenByID(ctx context.Context, id int64) (PasswordResetToken, error)
	GetPasswordResetTokenByToken(ctx context.Context, token string) (PasswordResetToken, error)
	// There is deliberately no "list every payment method" query. It was here for
	// the #12 fix and it was never routed, so deleting it removed a query whose
	// only behaviour is to hand back every card in the table to whoever asks.
	GetPaymentMethodByID(ctx context.Context, id int64) (PaymentMethod, error)
	GetPaymentMethodsByUserID(ctx context.Context, userID int64) ([]PaymentMethod, error)
	GetReviewByBookAndUser(ctx context.Context, arg GetReviewByBookAndUserParams) (Review, error)
	GetReviewByID(ctx context.Context, id int64) (Review, error)
	// Reviews are public to read, so the owner is needed only to decide who may
	// edit or delete one.
	GetReviewOwnerID(ctx context.Context, id int64) (int64, error)
	GetReviewsByBookID(ctx context.Context, bookID int64) ([]Review, error)
	// The authoritative account state for an authenticated request. The admin gate
	// reads role from here rather than from the token, so demoting a user takes
	// effect on the next request.
	GetSessionState(ctx context.Context, id int64) (GetSessionStateRow, error)
	// Locking the account row is what makes the conditional debit below actually
	// conditional on TiDB. In pessimistic mode an UPDATE that matched the read
	// snapshot still rewrites the row once the lock is granted, so two concurrent
	// checkouts could each see a balance of 1000 cents and both debit, driving it
	// to -1000 (TestBalanceCannotGoNegative caught it against the real cluster).
	// Acquiring the lock as the first statement of the transaction makes the later
	// UPDATE read current data and the loser fail its balance_cents >= ? check.
	GetUserBalanceForUpdate(ctx context.Context, id int64) (int64, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id int64) (User, error)
	// Returns a use when an order is abandoned after the coupon was spent, so a
	// failed checkout does not permanently consume a customer's single use.
	GiveBackCouponUse(ctx context.Context, id int64) error
	// Whether a customer actually bought a title.
	//
	// The join through order_items is what makes this a real purchase check: an
	// order row alone proves nothing, because the previous checkout accepted a
	// client-supplied total and could record an order that was never paid for.
	// A review has to be attached to a line on a completed order.
	//
	// EXISTS rather than a count, because the answer is a boolean and counting rows
	// that may be numerous tells nobody anything extra.
	HasPurchasedBook(ctx context.Context, arg HasPurchasedBookParams) (bool, error)
	IncrementBookStock(ctx context.Context, arg IncrementBookStockParams) error
	// The three panels' history, newest first. entity filters the view a tab asks
	// for; limit is pages of 200 so a history cannot grow an unbounded response.
	// The primary key is AUTO_RANDOM, so id order is not insert order: ORDER BY id DESC
	// returns a random slice of the table and the newest pages vanish behind LIMIT.
	// created_at is the true sequence of events; id only breaks same-millisecond ties.
	ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]AuditLog, error)
	// The moderation queue.
	//
	// The join is what makes the row useful in a table: a review on its own is a
	// rating and a paragraph, and the moderator's first question is always "of what,
	// by whom". Fetching that per row would be an N+1 in the one place where a
	// moderator is scrolling a queue, so it is done once in the database.
	//
	// Newest first, because a queue is worked from the top.
	ListReviewsForModeration(ctx context.Context) ([]ListReviewsForModerationRow, error)
	// The redemption, done as a single conditional update.
	//
	// used_count < max_uses and the expiry are both part of the WHERE clause, so two
	// concurrent redemptions of the last remaining use cannot both match: the second
	// one updates zero rows. The old code read the count, compared it in Go and
	// wrote it back, which is a time-of-check to time-of-use gap wide enough for a
	// dozen parallel requests to walk through together.
	//
	// The caller must check the returned row count. Zero means the coupon was
	// exhausted or expired, and the whole transaction has to be abandoned.
	RedeemCoupon(ctx context.Context, id int64) (int64, error)
	// Requesting a new code must invalidate the previous one, so an intercepted
	// older email cannot be used after the user asked for a fresh code.
	RevokePasswordResetTokensForUser(ctx context.Context, userID int64) (int64, error)
	// The "dar de baja" / "dar de alta" flip. The service bumps token_version when
	// taking somebody off, so the sessions they already hold die with it; this
	// statement only moves the bit.
	SetUserActive(ctx context.Context, arg SetUserActiveParams) (int64, error)
	// The role change is admin-only at the route, and AdminOnly re-reads the role
	// from this column on every admin request, so a forged claim does not survive
	// the change and a demoted administrator loses access immediately.
	SetUserRole(ctx context.Context, arg SetUserRoleParams) error
	// Revenue, not volume. The panel labels this figure what it is: money actually
	// taken. An order that was cancelled or refunded has had its money returned, so
	// summing it in would overstate the shop by exactly the refunds it granted.
	// 'pending' is not money taken either; nothing has been charged yet.
	//
	// The CAST is not decoration. MySQL widens SUM() over an integer column to
	// DECIMAL so the result cannot overflow, and the driver hands a DECIMAL back as
	// []byte. Left uncast, sqlc types the column as interface{}, and the store
	// received bytes it could only reject, which is why GET /admin/stats answered
	// 500 with "unexpected type for sum" and took the whole panel down with it.
	// CAST(... AS SIGNED) makes TiDB return BIGINT, so the sum is an int64 from the
	// wire to the JSON, and no amount of money passes through a float.
	SumOrderTotals(ctx context.Context) (interface{}, error)
	UpdateAddress(ctx context.Context, arg UpdateAddressParams) error
	UpdateBook(ctx context.Context, arg UpdateBookParams) error
	UpdateCoupon(ctx context.Context, arg UpdateCouponParams) error
	// user_id is absent on purpose. Reassigning an order to a different account is a
	// takeover primitive, and no caller should be able to do it by editing one.
	UpdateOrder(ctx context.Context, arg UpdateOrderParams) error
	UpdateOrderItem(ctx context.Context, arg UpdateOrderItemParams) error
	// Only the password column. Used by the reset flow so a password change can
	// never be combined with a mass-assigned email, role or balance.
	UpdatePasswordHash(ctx context.Context, arg UpdatePasswordHashParams) error
	UpdatePasswordResetToken(ctx context.Context, arg UpdatePasswordResetTokenParams) error
	// user_id is deliberately absent. Reassigning a card to another account is a
	// takeover primitive, and the handler already forces the stored owner.
	UpdatePaymentMethod(ctx context.Context, arg UpdatePaymentMethodParams) error
	UpdateReview(ctx context.Context, arg UpdateReviewParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) error
}

var _ Querier = (*Queries)(nil)
