// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reviews.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createReview = `-- name: CreateReview :execresult
INSERT INTO reviews (book_id, user_id, rating, comment, image_url)
VALUES (?, ?, ?, ?, ?)
`

type CreateReviewParams struct {
	BookID   int64          `json:"book_id"`
	UserID   int64          `json:"user_id"`
	Rating   int32          `json:"rating"`
	Comment  sql.NullString `json:"comment"`
	ImageUrl string         `json:"image_url"`
}

func (q *Queries) CreateReview(ctx context.Context, arg CreateReviewParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createReview,
		arg.BookID,
		arg.UserID,
		arg.Rating,
		arg.Comment,
		arg.ImageUrl,
	)
}

const deleteReview = `-- name: DeleteReview :exec
DELETE FROM reviews WHERE id = ?
`

func (q *Queries) DeleteReview(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteReview, id)
	return err
}

const getAllReviews = `-- name: GetAllReviews :many
SELECT id, book_id, user_id, rating, comment, image_url, created_at FROM reviews
`

func (q *Queries) GetAllReviews(ctx context.Context) ([]Review, error) {
	rows, err := q.db.QueryContext(ctx, getAllReviews)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Review{}
	for rows.Next() {
		var i Review
		if err := rows.Scan(
			&i.ID,
			&i.BookID,
			&i.UserID,
			&i.Rating,
			&i.Comment,
			&i.ImageUrl,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getReviewByBookAndUser = `-- name: GetReviewByBookAndUser :one
SELECT id, book_id, user_id, rating, comment, image_url, created_at FROM reviews WHERE book_id = ? AND user_id = ?
`

type GetReviewByBookAndUserParams struct {
	BookID int64 `json:"book_id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) GetReviewByBookAndUser(ctx context.Context, arg GetReviewByBookAndUserParams) (Review, error) {
	row := q.db.QueryRowContext(ctx, getReviewByBookAndUser, arg.BookID, arg.UserID)
	var i Review
	err := row.Scan(
		&i.ID,
		&i.BookID,
		&i.UserID,
		&i.Rating,
		&i.Comment,
		&i.ImageUrl,
		&i.CreatedAt,
	)
	return i, err
}

const getReviewByID = `-- name: GetReviewByID :one
SELECT id, book_id, user_id, rating, comment, image_url, created_at FROM reviews WHERE id = ?
`

func (q *Queries) GetReviewByID(ctx context.Context, id int64) (Review, error) {
	row := q.db.QueryRowContext(ctx, getReviewByID, id)
	var i Review
	err := row.Scan(
		&i.ID,
		&i.BookID,
		&i.UserID,
		&i.Rating,
		&i.Comment,
		&i.ImageUrl,
		&i.CreatedAt,
	)
	return i, err
}

const getReviewOwnerID = `-- name: GetReviewOwnerID :one
SELECT user_id FROM reviews WHERE id = ?
`

// Reviews are public to read, so the owner is needed only to decide who may
// edit or delete one.
func (q *Queries) GetReviewOwnerID(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, getReviewOwnerID, id)
	var user_id int64
	err := row.Scan(&user_id)
	return user_id, err
}

const getReviewsByBookID = `-- name: GetReviewsByBookID :many
SELECT id, book_id, user_id, rating, comment, image_url, created_at FROM reviews WHERE book_id = ?
`

func (q *Queries) GetReviewsByBookID(ctx context.Context, bookID int64) ([]Review, error) {
	rows, err := q.db.QueryContext(ctx, getReviewsByBookID, bookID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Review{}
	for rows.Next() {
		var i Review
		if err := rows.Scan(
			&i.ID,
			&i.BookID,
			&i.UserID,
			&i.Rating,
			&i.Comment,
			&i.ImageUrl,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const hasPurchasedBook = `-- name: HasPurchasedBook :one
SELECT EXISTS (
    SELECT 1
    FROM order_items oi
    JOIN orders o ON o.id = oi.order_id
    WHERE oi.book_id = ?
      AND o.user_id = ?
      AND o.status = 'completed'
)
`

type HasPurchasedBookParams struct {
	BookID int64 `json:"book_id"`
	UserID int64 `json:"user_id"`
}

// Whether a customer actually bought a title.
//
// The join through order_items is what makes this a real purchase check: an
// order row alone proves nothing, because the previous checkout accepted a
// client-supplied total and could record an order that was never paid for.
// A review has to be attached to a line on a completed order.
//
// EXISTS rather than a count, because the answer is a boolean and counting rows
// that may be numerous tells nobody anything extra.
func (q *Queries) HasPurchasedBook(ctx context.Context, arg HasPurchasedBookParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, hasPurchasedBook, arg.BookID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listReviewsForModeration = `-- name: ListReviewsForModeration :many
SELECT
    r.id,
    r.book_id,
    b.title AS book_title,
    r.user_id,
    u.email AS author_email,
    r.rating,
    r.comment,
    r.image_url,
    r.created_at
FROM reviews r
JOIN books b ON b.id = r.book_id
JOIN users u ON u.id = r.user_id
ORDER BY r.id DESC
`

type ListReviewsForModerationRow struct {
	ID          int64          `json:"id"`
	BookID      int64          `json:"book_id"`
	BookTitle   string         `json:"book_title"`
	UserID      int64          `json:"user_id"`
	AuthorEmail string         `json:"author_email"`
	Rating      int32          `json:"rating"`
	Comment     sql.NullString `json:"comment"`
	ImageUrl    string         `json:"image_url"`
	CreatedAt   time.Time      `json:"created_at"`
}

// The moderation queue.
//
// The join is what makes the row useful in a table: a review on its own is a
// rating and a paragraph, and the moderator's first question is always "of what,
// by whom". Fetching that per row would be an N+1 in the one place where a
// moderator is scrolling a queue, so it is done once in the database.
//
// Newest first, because a queue is worked from the top.
func (q *Queries) ListReviewsForModeration(ctx context.Context) ([]ListReviewsForModerationRow, error) {
	rows, err := q.db.QueryContext(ctx, listReviewsForModeration)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListReviewsForModerationRow{}
	for rows.Next() {
		var i ListReviewsForModerationRow
		if err := rows.Scan(
			&i.ID,
			&i.BookID,
			&i.BookTitle,
			&i.UserID,
			&i.AuthorEmail,
			&i.Rating,
			&i.Comment,
			&i.ImageUrl,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateReview = `-- name: UpdateReview :exec
UPDATE reviews
SET book_id = ?, user_id = ?, rating = ?, comment = ?, image_url = ?
WHERE id = ?
`

type UpdateReviewParams struct {
	BookID   int64          `json:"book_id"`
	UserID   int64          `json:"user_id"`
	Rating   int32          `json:"rating"`
	Comment  sql.NullString `json:"comment"`
	ImageUrl string         `json:"image_url"`
	ID       int64          `json:"id"`
}

func (q *Queries) UpdateReview(ctx context.Context, arg UpdateReviewParams) error {
	_, err := q.db.ExecContext(ctx, updateReview,
		arg.BookID,
		arg.UserID,
		arg.Rating,
		arg.Comment,
		arg.ImageUrl,
		arg.ID,
	)
	return err
}
