// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"
	"database/sql"
)

const bumpTokenVersion = `-- name: BumpTokenVersion :exec
UPDATE users
SET token_version = token_version + 1
WHERE id = ?
`

// Invalidates every session issued before this call: the middleware compares the
// token's "ver" claim against this value on each request.
func (q *Queries) BumpTokenVersion(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, bumpTokenVersion, id)
	return err
}

const countUsers = `-- name: CountUsers :one
SELECT count(*) FROM users
`

// Dashboard aggregate. Stats used to call GetAllUsers and take len() of the
// result, so asking for one number cost a full table read and a full
// materialisation of every user in the shop.
func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :execresult
INSERT INTO users (first_name, last_name, email, password_hash, role)
VALUES (?, ?, ?, ?, ?)
`

type CreateUserParams struct {
	FirstName    string `json:"first_name"`
	LastName     string `json:"last_name"`
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
	Role         string `json:"role"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createUser,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.PasswordHash,
		arg.Role,
	)
}

const creditUserBalance = `-- name: CreditUserBalance :exec
UPDATE users
SET balance_cents = balance_cents + ?
WHERE id = ?
`

type CreditUserBalanceParams struct {
	BalanceCents int64 `json:"balance_cents"`
	ID           int64 `json:"id"`
}

// The refund half of a debit. Used when an order is cancelled, and it is the
// only way a balance goes up outside the seed.
func (q *Queries) CreditUserBalance(ctx context.Context, arg CreditUserBalanceParams) error {
	_, err := q.db.ExecContext(ctx, creditUserBalance, arg.BalanceCents, arg.ID)
	return err
}

const debitUserBalance = `-- name: DebitUserBalance :exec
UPDATE users SET balance_cents = balance_cents - ? WHERE id = ?
`

type DebitUserBalanceParams struct {
	BalanceCents int64 `json:"balance_cents"`
	ID           int64 `json:"id"`
}

func (q *Queries) DebitUserBalance(ctx context.Context, arg DebitUserBalanceParams) error {
	_, err := q.db.ExecContext(ctx, debitUserBalance, arg.BalanceCents, arg.ID)
	return err
}

const debitUserBalanceIfSufficient = `-- name: DebitUserBalanceIfSufficient :execrows
UPDATE users
SET balance_cents = balance_cents - ?
WHERE id = ? AND balance_cents >= ?
`

type DebitUserBalanceIfSufficientParams struct {
	BalanceCents   int64 `json:"balance_cents"`
	ID             int64 `json:"id"`
	BalanceCents_2 int64 `json:"balance_cents_2"`
}

// The debit and the affordability check are the same statement.
//
// The old DebitUserBalance subtracted unconditionally, after the service had
// read the balance and compared it in Go. Two requests spending the same balance
// both read a sufficient figure and both debited, driving it negative. With the
// comparison in the WHERE clause the second update matches no rows, and the
// caller sees zero affected and aborts.
//
// RowsAffected is the answer; there is nothing to read afterwards.
func (q *Queries) DebitUserBalanceIfSufficient(ctx context.Context, arg DebitUserBalanceIfSufficientParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, debitUserBalanceIfSufficient, arg.BalanceCents, arg.ID, arg.BalanceCents_2)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteUser = `-- name: DeleteUser :execrows
DELETE FROM users WHERE id = ?
`

// As :exec, deleting an account that does not exist was indistinguishable from
// deleting one that did, and the panel reported the success either way. Zero
// rows becomes sql.ErrNoRows at the store, which is a 404.
func (q *Queries) DeleteUser(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteUser, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getAllUsers = `-- name: GetAllUsers :many
SELECT id, first_name, last_name, email, password_hash, role, balance_cents, token_version, created_at, is_active FROM users
`

func (q *Queries) GetAllUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, getAllUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.PasswordHash,
			&i.Role,
			&i.BalanceCents,
			&i.TokenVersion,
			&i.CreatedAt,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSessionState = `-- name: GetSessionState :one
SELECT id, email, role, token_version, is_active
FROM users WHERE id = ?
`

type GetSessionStateRow struct {
	ID           int64  `json:"id"`
	Email        string `json:"email"`
	Role         string `json:"role"`
	TokenVersion int32  `json:"token_version"`
	IsActive     bool   `json:"is_active"`
}

// The authoritative account state for an authenticated request. The admin gate
// reads role from here rather than from the token, so demoting a user takes
// effect on the next request.
func (q *Queries) GetSessionState(ctx context.Context, id int64) (GetSessionStateRow, error) {
	row := q.db.QueryRowContext(ctx, getSessionState, id)
	var i GetSessionStateRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Role,
		&i.TokenVersion,
		&i.IsActive,
	)
	return i, err
}

const getUserBalanceForUpdate = `-- name: GetUserBalanceForUpdate :one
SELECT balance_cents
FROM users
WHERE id = ?
FOR UPDATE
`

// Locking the account row is what makes the conditional debit below actually
// conditional on TiDB. In pessimistic mode an UPDATE that matched the read
// snapshot still rewrites the row once the lock is granted, so two concurrent
// checkouts could each see a balance of 1000 cents and both debit, driving it
// to -1000 (TestBalanceCannotGoNegative caught it against the real cluster).
// Acquiring the lock as the first statement of the transaction makes the later
// UPDATE read current data and the loser fail its balance_cents >= ? check.
func (q *Queries) GetUserBalanceForUpdate(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, getUserBalanceForUpdate, id)
	var balance_cents int64
	err := row.Scan(&balance_cents)
	return balance_cents, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, first_name, last_name, email, password_hash, role, balance_cents, token_version, created_at, is_active FROM users WHERE email = ?
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.BalanceCents,
		&i.TokenVersion,
		&i.CreatedAt,
		&i.IsActive,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, first_name, last_name, email, password_hash, role, balance_cents, token_version, created_at, is_active FROM users WHERE id = ?
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.BalanceCents,
		&i.TokenVersion,
		&i.CreatedAt,
		&i.IsActive,
	)
	return i, err
}

const setUserActive = `-- name: SetUserActive :execrows
UPDATE users
SET is_active = ?
WHERE id = ?
`

type SetUserActiveParams struct {
	IsActive bool  `json:"is_active"`
	ID       int64 `json:"id"`
}

// The "dar de baja" / "dar de alta" flip. The service bumps token_version when
// taking somebody off, so the sessions they already hold die with it; this
// statement only moves the bit.
func (q *Queries) SetUserActive(ctx context.Context, arg SetUserActiveParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setUserActive, arg.IsActive, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setUserRole = `-- name: SetUserRole :exec
UPDATE users
SET role = ?
WHERE id = ?
`

type SetUserRoleParams struct {
	Role string `json:"role"`
	ID   int64  `json:"id"`
}

// The role change is admin-only at the route, and AdminOnly re-reads the role
// from this column on every admin request, so a forged claim does not survive
// the change and a demoted administrator loses access immediately.
func (q *Queries) SetUserRole(ctx context.Context, arg SetUserRoleParams) error {
	_, err := q.db.ExecContext(ctx, setUserRole, arg.Role, arg.ID)
	return err
}

const updatePasswordHash = `-- name: UpdatePasswordHash :exec
UPDATE users
SET password_hash = ?
WHERE id = ?
`

type UpdatePasswordHashParams struct {
	PasswordHash string `json:"password_hash"`
	ID           int64  `json:"id"`
}

// Only the password column. Used by the reset flow so a password change can
// never be combined with a mass-assigned email, role or balance.
func (q *Queries) UpdatePasswordHash(ctx context.Context, arg UpdatePasswordHashParams) error {
	_, err := q.db.ExecContext(ctx, updatePasswordHash, arg.PasswordHash, arg.ID)
	return err
}

const updateUser = `-- name: UpdateUser :exec
UPDATE users
SET first_name = ?, last_name = ?, email = ?, password_hash = ?, role = ?, balance_cents = ?
WHERE id = ?
`

type UpdateUserParams struct {
	FirstName    string `json:"first_name"`
	LastName     string `json:"last_name"`
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
	Role         string `json:"role"`
	BalanceCents int64  `json:"balance_cents"`
	ID           int64  `json:"id"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.ExecContext(ctx, updateUser,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.PasswordHash,
		arg.Role,
		arg.BalanceCents,
		arg.ID,
	)
	return err
}
