package transport

import (
	"bytes"
	"crypto/rand"
	"encoding/hex"
	"errors"
	"fmt"
	"image"
	"image/gif"
	"image/jpeg"
	"image/png"
	"io"
	"log/slog"
	"net/http"
	"os"
	"path/filepath"
	"strings"

	// Registered for their decoders, not for the HTTP layer. image.Decode reads
	// the format from the file's own header, so this is the sniff that matters:
	// whatever the client called the upload.
	_ "image/gif"
)

const (
	// maxUploadBytes caps a single image. The body is read through a
	// MaxBytesReader, so a client cannot stream past this and fill the disk.
	maxUploadBytes = 5 << 20 // 5 MiB
	// maxPixels bounds decompression. A 60 KB file can expand to gigabytes of
	// RGBA, so the byte cap alone does not bound the work done to decode it.
	maxPixels = 40_000_000 // ~40 MP, about a 12 MP photo with room to spare
	// maxDimension is the other half of the bound, for images that are narrow
	// and enormously tall.
	maxDimension = 12_000
)

// errNotAnImage is returned for anything the decoders do not recognise.
var errNotAnImage = errors.New("unsupported image format")

// imageFormats is the closed set the server will store. Every entry is a raster
// format: nothing here can carry script, and the response's content-type is
// derived from this table rather than from anything the client sent.
//
// SVG is absent deliberately. An SVG is a document, so serving one as
// image/svg+xml gives its <script> the page's origin, the DOM and the session
// cookie. It is also the format the old handler accepted, which is what made #17
// exploitable rather than theoretical.
//
// WebP is absent for the same reason, one step removed. The standard library can
// decode JPEG, PNG and GIF, and it can re-encode all three, so every entry below
// has a real re-encoder and no byte of the upload survives undecoded. WebP has
// no decoder in image/, so accepting it would mean storing the client's bytes
// verbatim, with only a two-magic-byte check and nosniff between them and the
// browser. A format the server cannot take apart is a format it cannot vouch
// for, and review images do not need one: every browser that can capture a
// photo can produce a JPEG.
var imageFormats = map[string]imageFormat{
	".png": {ext: ".png", contentType: "image/png", encode: encodePNG},
	".jpg": {ext: ".jpg", contentType: "image/jpeg", encode: encodeJPEG},
	".gif": {ext: ".gif", contentType: "image/gif", encode: encodeGIF},
}

// imageFormat is one entry of the closed set the server will store.
type imageFormat struct {
	// ext is generated by the server, never taken from the client.
	ext string
	// contentType is what Serve sends, and it comes from here.
	contentType string
	// encode writes the decoded image in this format. There is no nil case: an
	// entry without a re-encoder would be stored exactly as it arrived, which is
	// the thing this handler exists to prevent.
	encode func(io.Writer, image.Image) error
}

// UploadHandler stores and serves review images.
type UploadHandler struct {
	dir string
}

func NewUploadHandler(dir string) *UploadHandler {
	return &UploadHandler{dir: dir}
}

// Create accepts an image, re-encodes it, and stores it under a name the server
// chose.
//
// The old handler wrote the client's bytes to disk under the client's filename
// and served the result with a content-type derived from its extension. That is
// three holes stacked: the extension chose the content-type, so an .svg became
// image/svg+xml and its script ran on our origin; the filename came from the
// client, so a name could be crafted; and the bytes were never parsed, so
// anything could be stored.
//
// Decoding and re-encoding closes all three at once. A file that is not a
// picture does not decode. A picture with a script inside it is decoded into
// pixels, and a script has no meaning once it is pixels. The name and the
// content-type are both ours.
func (h *UploadHandler) Create(w http.ResponseWriter, r *http.Request) {
	// Before anything reads the body.
	r.Body = http.MaxBytesReader(w, r.Body, maxUploadBytes+maxUploadBytes/10)

	if err := r.ParseMultipartForm(maxUploadBytes); err != nil {
		writeError(w, http.StatusBadRequest, errors.New("invalid multipart form"))
		return
	}
	file, header, err := r.FormFile("image")
	if err != nil {
		writeError(w, http.StatusBadRequest, errors.New("missing image file"))
		return
	}
	defer file.Close()

	if header.Size > maxUploadBytes {
		writeError(w, http.StatusRequestEntityTooLarge,
			fmt.Errorf("image is larger than %d bytes", maxUploadBytes))
		return
	}

	// The extension is a hint for humans, and only humans: it is read here to
	// choose the encoder, never to name the file or to set a content-type.
	ext := strings.ToLower(filepath.Ext(header.Filename))
	format, ok := imageFormats[ext]
	if !ok {
		writeError(w, http.StatusUnsupportedMediaType,
			fmt.Errorf("unsupported image type; use one of jpg, png or gif"))
		return
	}

	raw, err := io.ReadAll(io.LimitReader(file, maxUploadBytes+1))
	if err != nil {
		writeError(w, http.StatusBadRequest, errors.New("could not read the uploaded file"))
		return
	}
	if len(raw) == 0 {
		writeError(w, http.StatusBadRequest, errors.New("the uploaded file is empty"))
		return
	}
	if len(raw) > maxUploadBytes {
		writeError(w, http.StatusRequestEntityTooLarge,
			fmt.Errorf("image is larger than %d bytes", maxUploadBytes))
		return
	}

	stored, err := reencode(raw, format)
	if err != nil {
		// A file that claims to be a jpeg and is not never reaches the disk. The
		// client's extension is a claim, and this is where it gets checked
		// against the bytes.
		if errors.Is(err, errNotAnImage) {
			writeError(w, http.StatusUnsupportedMediaType, err)
			return
		}
		writeError(w, http.StatusBadRequest, err)
		return
	}

	if err := os.MkdirAll(h.dir, 0o755); err != nil {
		slog.Error("could not create the upload directory", "err", err)
		writeError(w, http.StatusInternalServerError, err)
		return
	}

	name, err := h.store(stored, format)
	if err != nil {
		slog.Error("could not store the upload", "err", err)
		writeError(w, http.StatusInternalServerError, err)
		return
	}

	writeJSON(w, http.StatusCreated, map[string]string{"url": "/uploads/" + name})
}

// store writes the re-encoded bytes under a fresh random name. The name comes
// from crypto/rand and not from the clock, the client, or anything else
// predictable: a guessable name is a guessable overwrite.
func (h *UploadHandler) store(data []byte, format imageFormat) (string, error) {
	buf := make([]byte, 16)
	if _, err := rand.Read(buf); err != nil {
		return "", err
	}
	name := hex.EncodeToString(buf) + format.ext
	if err := os.WriteFile(filepath.Join(h.dir, name), data, 0o644); err != nil {
		return "", err
	}
	return name, nil
}

// reencode decodes the bytes and writes them back out, discarding everything
// that is not pixels.
//
// The decode is the security boundary, not a validation step. Only the pixels
// that come out of it are ever stored, so whatever else the file contained is
// gone by the time the bytes hit the disk.
func reencode(raw []byte, format imageFormat) ([]byte, error) {
	if format.encode == nil {
		// Unreachable while every entry in imageFormats has an encoder, and
		// kept as a refusal rather than a pass-through on purpose: the day
		// someone adds a format and forgets the encoder, the file is rejected,
		// not stored verbatim.
		return nil, errors.New("no encoder for this image format")
	}

	img, formatName, err := image.Decode(bytes.NewReader(raw))
	if err != nil {
		return nil, errNotAnImage
	}

	b := img.Bounds()
	if b.Dx() <= 0 || b.Dy() <= 0 {
		return nil, errors.New("the image has no pixels")
	}
	if b.Dx() > maxDimension || b.Dy() > maxDimension {
		return nil, fmt.Errorf("the image is %dx%d, larger than %d pixels on a side",
			b.Dx(), b.Dy(), maxDimension)
	}
	if int64(b.Dx())*int64(b.Dy()) > maxPixels {
		return nil, fmt.Errorf("the image has %d pixels, more than the %d allowed",
			int64(b.Dx())*int64(b.Dy()), maxPixels)
	}

	// Ask the format we are about to write, not the one that arrived. It only
	// matters for JPEG, which is lossy, but knowing the source is worth logging.
	_ = formatName

	var out bytes.Buffer
	if err := format.encode(&out, img); err != nil {
		return nil, fmt.Errorf("could not encode the image: %w", err)
	}
	return out.Bytes(), nil
}

func encodePNG(w io.Writer, img image.Image) error {
	return png.Encode(w, img)
}

func encodeJPEG(w io.Writer, img image.Image) error {
	// 90 keeps photographs visually intact at review-thumbnail size and drops
	// the metadata, which is where a GPS coordinate or a camera serial would
	// otherwise survive into a public directory.
	return jpeg.Encode(w, img, &jpeg.Options{Quality: 90})
}

func encodeGIF(w io.Writer, img image.Image) error {
	return gif.Encode(w, img, nil)
}

// Serve returns a stored image with a content-type from the closed table above.
//
// It no longer uses http.ServeFile, which derives the type from the file's
// extension and would happily serve anything that got written to the directory.
// The mapping is exhaustive: a name whose extension is not in the table is a 404,
// so a file that somehow landed on disk by another route is still not served.
func (h *UploadHandler) Serve(w http.ResponseWriter, r *http.Request) {
	name := r.PathValue("name")
	if name == "" || filepath.Base(name) != name || strings.Contains(name, "..") {
		writeError(w, http.StatusBadRequest, errors.New("invalid file name"))
		return
	}

	format, ok := imageFormats[strings.ToLower(filepath.Ext(name))]
	if !ok {
		writeError(w, http.StatusNotFound, errors.New("not found"))
		return
	}

	// A %00 in the path would be a second name for a file the table just
	// rejected.
	if strings.ContainsRune(name, 0) {
		writeError(w, http.StatusBadRequest, errors.New("invalid file name"))
		return
	}

	f, err := os.Open(filepath.Join(h.dir, name))
	if err != nil {
		writeError(w, http.StatusNotFound, errors.New("not found"))
		return
	}
	defer f.Close()

	head := w.Header()
	head.Set("Content-Type", format.contentType)
	// Without nosniff a browser may still second-guess the declared type, and
	// the whole reason for the closed table is that it must not get a chance.
	head.Set("X-Content-Type-Options", "nosniff")
	// inline so the image renders in an <img>, which is the only thing these
	// files are for.
	head.Set("Content-Disposition", "inline")
	// Uploads are user-supplied content. They are never a valid part of this
	// application's own documents, so they are sandboxed out of the origin as
	// well: even a decoding bug in a browser should not reach our cookies.
	head.Set("Content-Security-Policy", "default-src 'none'; sandbox")
	// The name is random and never reused, so the bytes at a URL are final.
	head.Set("Cache-Control", "public, max-age=31536000, immutable")

	if _, err := io.Copy(w, f); err != nil {
		return // the client hung up mid-response; nothing useful to add
	}
}
